name: Default workflow
on: [push]

jobs:
  linux-job:
    runs-on: ubuntu-latest
    steps:
      - name: Runner's name
        run: hostname
      - name: Operative system
        run: cat /etc/os-release

  mac-job:
    runs-on: macos-latest
    steps:
      - name: Runner's name
        run: hostname
      - name: Operative system
        run: sw_vers

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Runner's name
        run: hostname
      - name: Operative system
        run: systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version"
